M48
; DRILL file {KiCad 8.0.4} date 2025-01-06T15:09:26+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-06T15:09:26+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X85.0Y-53.407
X85.0Y-55.125
X85.0Y-56.807
T2
X52.5Y-53.855
X52.5Y-56.395
M30
